import pandas as pd
import glob
import os

def compile_results_for_paper():
    # 1. Locate all the individual result CSVs generated by your models
    files = glob.glob("all_species_results_*.csv")
    
    if not files:
        print("Error: No 'all_species_results_*.csv' files found in the directory.")
        return
        
    print(f"Found {len(files)} result files. Compiling data...")
    
    # 2. Read, clean headers, and store dataframes
    df_list = []
    for f in files:
        df = pd.read_csv(f)
        # CRITICAL FIX: Clean up potential whitespace BEFORE concatenating
        df.columns = df.columns.str.strip()
        df_list.append(df)
        
    # 3. Concatenate cleanly aligned columns
    combined_df = pd.concat(df_list, ignore_index=True)
    
    # 4. Save the master combined dataset (Raw Data for Supp. Info)
    combined_file = "paper_full_raw_results.csv"
    combined_df.to_csv(combined_file, index=False)
    print(f"[✔] Saved complete raw dataset -> {combined_file}")
    
    # 5. Generate the Summary Table for the actual paper
    numeric_cols = combined_df.select_dtypes(include=['number']).columns
    summary_df = combined_df.groupby('label')[numeric_cols].mean().reset_index()
    
    # Sort by MCC as the primary biological indicator
    if 'mcc' in summary_df.columns:
        summary_df = summary_df.sort_values(by='mcc', ascending=False)
    
    # Round to 3 decimal places for standard academic formatting
    summary_df = summary_df.round(3)
    
    # Rename columns to look professional in a publication table
    rename_map = {
        'label': 'Model_Strategy',
        'accuracy': 'Accuracy',
        'precision': 'Precision',
        'recall': 'Recall',
        'f1': 'F1_Score',
        'mcc': 'MCC',
        'mae': 'MAE_(bp)',
        'exact_rate': 'Exact_Match_Rate',
        'specificity': 'Specificity',
        'balanced_accuracy': 'Balanced_Accuracy'
    }
    summary_df = summary_df.rename(columns=rename_map)
    
    # 6. Save the summary table
    summary_file = "paper_summary_table.csv"
    summary_df.to_csv(summary_file, index=False)
    print(f"[✔] Saved summarized publication table -> {summary_file}")

if __name__ == "__main__":
    compile_results_for_paper()